version: '3'
services:
  app:
    build:
      target: development
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - TOKEN=5831017982:AAE8S2FIZkHBWq90_R2ZVbHxnsalSZfTHzc
      - API=https://dev.sellershub.ru/api
    volumes:
      - ./app:/usr/src/app