version: '3'
services:
  app:
    build:
      target: development
    command: npm run start:dev
    env_file:
      - ./app/envs/.development.env
    volumes:
      - ./app:/usr/src/app
  app_db:
    volumes:
      - app_db-data-dev:/var/lib/postgresql/data


  