version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    container_name: catalog-bot-app
    environment:
      - NODE_ENV=production
      - TOKEN=5831017982:AAE8S2FIZkHBWq90_R2ZVbHxnsalSZfTHzc
      - API=https://sellershub.ru/api
    networks:
      - catalog-bot-network


networks:
  catalog-bot-network:
    driver: bridge
